<a href="https://colab.research.google.com/github/Ritansh-7/Chatbot/blob/main/nb/Llama_FP8_GRPO.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

To run this, press "*Runtime*" and press "*Run all*" on a **free** Tesla T4 Google Colab instance!
<div class="align-center">
<a href="https://unsloth.ai/"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
<a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord button.png" width="145"></a>
<a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a> Join Discord if you need help + ⭐ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐
</div>

To install Unsloth on your local device, follow [our guide](https://unsloth.ai/docs/get-started/install). This notebook is licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme).

You will learn how to do [data prep](#Data), how to [train](#Train), how to [run the model](#Inference), & how to save it

### News

Introducing **Unsloth Studio** - a new open source, no-code web UI to train and run LLMs. [Blog](https://unsloth.ai/docs/new/studio) • [Notebook](https://colab.research.google.com/github/unslothai/unsloth/blob/main/studio/Unsloth_Studio_Colab.ipynb)

<table><tr>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FxV1PO5DbF3ksB51nE2Tw%252Fmore%2520cropped%2520ui%2520for%2520homepage.png%3Falt%3Dmedia%26token%3Df75942c9-3d8d-4b59-8ba2-1a4a38de1b86&width=376&dpr=3&quality=100&sign=a663c397&sv=2" width="200" height="120" alt="Unsloth Studio Training UI"></a><br><sub><b>Train models</b> — no code needed</sub></td>
<td align="center"><a href="https://unsloth.ai/docs/new/studio"><img src="https://unsloth.ai/docs/~gitbook/image?url=https%3A%2F%2F3215535692-files.gitbook.io%2F~%2Ffiles%2Fv0%2Fb%2Fgitbook-x-prod.appspot.com%2Fo%2Fspaces%252FxhOjnexMCB3dmuQFQ2Zq%252Fuploads%252FRCnTAZ6Uh88DIlU3g0Ij%252Fmainpage%2520unsloth.png%3Falt%3Dmedia%26token%3D837c96b6-bd09-4e81-bc76-fa50421e9bfb&width=376&dpr=3&quality=100&sign=c1a39da1&sv=2" width="200" height="120" alt="Unsloth Studio Chat UI"></a><br><sub><b>Run GGUF models</b> on Mac, Windows & Linux</sub></td>
</tr></table>

Train MoEs - DeepSeek, GLM, Qwen and gpt-oss 12x faster with 35% less VRAM. [Blog](https://unsloth.ai/docs/new/faster-moe)

Ultra Long-Context Reinforcement Learning is here with 7x more context windows! [Blog](https://unsloth.ai/docs/new/grpo-long-context)

New in Reinforcement Learning: [FP8 RL](https://unsloth.ai/docs/new/fp8-reinforcement-learning) • [Vision RL](https://unsloth.ai/docs/new/vision-reinforcement-learning-vlm-rl) • [Standby](https://unsloth.ai/docs/basics/memory-efficient-rl) • [gpt-oss RL](https://unsloth.ai/docs/new/gpt-oss-reinforcement-learning)

Visit our docs for all our [model uploads](https://unsloth.ai/docs/get-started/unsloth-model-catalog) and [notebooks](https://unsloth.ai/docs/get-started/unsloth-notebooks).

### Installation

In [1]:
%%capture
import os
os.environ["UNSLOTH_VLLM_STANDBY"] = "1" # [NEW] Extra 30% context lengths!
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install or uv pip install
    !pip install unsloth vllm
else:
    pass # For Colab / Kaggle, we need extra instructions hidden below \/

In [2]:
#@title Colab Extra Install { display-mode: "form" }
%%capture
import os
!pip install --upgrade -qqq uv
if "COLAB_" not in "".join(os.environ.keys()):
    # If you're not in Colab, just use pip install!
    !pip install unsloth vllm
else:
    try: import numpy, PIL; _numpy = f'numpy=={numpy.__version__}'; _pil = f'pillow=={PIL.__version__}'
    except: _numpy = "numpy"; _pil = "pillow"
    try: import subprocess; is_t4 = "Tesla T4" in str(subprocess.check_output(["nvidia-smi"]))
    except: is_t4 = False
    _vllm, _triton = ('vllm==0.9.2', 'triton==3.2.0') if is_t4 else ('vllm==0.15.1', 'triton')
    !uv pip install -qqq --upgrade {_vllm} {_numpy} {_pil} torchvision bitsandbytes xformers unsloth
    !uv pip install -qqq {_triton}
!uv pip install transformers==4.56.2
!uv pip install --no-deps trl==0.22.2

### Unsloth

Goal: To convert `Llama-3.2-1B-Instruct` into a reasoning model via GRPO by using OpenR1's Math dataset.

We first pre fine-tune the model to make GRPO skip trying to match formatting - this speeds GRPO up.

In [5]:
import os
os.environ['UNSLOTH_VLLM_STANDBY'] = "1" # Unsloth Standby reduces VRAM by 30%+
from unsloth import FastLanguageModel
import torch
max_seq_length = 2048 # Can increase for longer reasoning traces
lora_rank = 32 # Larger rank = smarter, but slower

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name = "unsloth/Llama-3.2-1B-Instruct",
    max_seq_length = max_seq_length,
    load_in_4bit = False, # False for LoRA 16bit
    fast_inference = True, # Enable vllm fast inference
    max_lora_rank = lora_rank,
    load_in_fp8 = False, # Float8 RL / GRPO! - Changed to False to fix vLLM configuration error on T4.
)

model = FastLanguageModel.get_peft_model(
    model,
    r = lora_rank, # Choose any number > 0 ! Suggested 8, 16, 32, 64, 128
    target_modules = [
        "q_proj", "k_proj", "v_proj", "o_proj",
        "gate_proj", "up_proj", "down_proj",
    ],
    lora_alpha = lora_rank*2, # *2 speeds up training
    use_gradient_checkpointing = "unsloth", # Reduces memory usage
    random_state = 3407,
)

INFO 03-31 11:18:54 [vllm_utils.py:724] Unsloth: Patching vLLM v1 graph capture
INFO 03-31 11:18:54 [vllm_utils.py:753] Unsloth: Patching vLLM v0 graph capture
==((====))==  Unsloth 2026.3.17: Fast Llama patching. Transformers: 4.56.2. vLLM: 0.9.2.
   \\   /|    Tesla T4. Num GPUs = 1. Max memory: 14.563 GB. Platform: Linux.
O^O/ \_/ \    Torch: 2.7.0+cu126. CUDA: 7.5. CUDA Toolkit: 12.6. Triton: 3.2.0
\        /    Bfloat16 = FALSE. FA [Xformers = 0.0.30. FA2 = False]
 "-____-"     Free license: http://github.com/unslothai/unsloth
Unsloth: Fast downloading is enabled - ignore downloading bars which are red colored!
Unsloth: Standby mode is enabled. Changing `gpu_memory_utilization` to 0.8.
Unsloth: vLLM loading unsloth/Llama-3.2-1B-Instruct with actual GPU utilization = 79.22%
Unsloth: Your GPU has CUDA compute capability 7.5 with VRAM = 14.56 GB.
Unsloth: Using conservativeness = 1.0. Chunked prefill tokens = 2048. Num Sequences = 48.
Unsloth: vLLM's KV Cache can use up to 9.04 GB. Also swap space = 0 GB.
Unsloth: `cudagraph_mode` is not in `from vllm.config import CompilationConfig`
Unsloth: Disabling `disable_cascade_attn` in vLLM to allow for better on policy RL!
INFO 03-31 11:19:02 [config.py:841] This model supports multiple tasks: {'generate', 'embed', 'classify', 'reward'}. Defaulting to 'generate'.
WARNING 03-31 11:19:02 [config.py:3371] Casting torch.bfloat16 to torch.float16.
INFO 03-31 11:19:02 [config.py:1472] Using max model len 2048
INFO 03-31 11:19:02 [config.py:2285] Chunked prefill is enabled with max_num_batched_tokens=4096.
INFO 03-31 11:19:02 [llm_engine.py:230] Initializing a V0 LLM engine (v0.9.2) with config: model='unsloth/Llama-3.2-1B-Instruct', speculative_config=None, tokenizer='unsloth/Llama-3.2-1B-Instruct', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, override_neuron_config={}, tokenizer_revision=None, trust_remote_code=False, dtype=torch.float16, max_seq_len=2048, download_dir=None, load_format=LoadFormat.AUTO, tensor_parallel_size=1, pipeline_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=False, kv_cache_dtype=auto,  device_config=cuda, decoding_config=DecodingConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_backend=''), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None), seed=0, served_model_name=unsloth/Llama-3.2-1B-Instruct, num_scheduler_steps=1, multi_step_stream_outputs=True, enable_prefix_caching=True, chunked_prefill_enabled=True, use_async_output_proc=True, pooler_config=None, compilation_config={"level":0,"debug_dump_path":"","cache_dir":"","backend":"inductor","custom_ops":[],"splitting_ops":[],"use_inductor":true,"compile_sizes":[],"inductor_compile_config":{"epilogue_fusion":true,"max_autotune":false,"shape_padding":true,"trace.enabled":false,"triton.cudagraphs":true,"debug":false,"dce":true,"memory_planning":true,"coordinate_descent_tuning":false,"trace.graph_diagram":false,"compile_threads":4,"group_fusion":true,"disable_progress":false,"verbose_progress":true,"triton.multi_kernel":0,"triton.use_block_ptr":true,"triton.enable_persistent_tma_matmul":true,"triton.autotune_at_compile_time":false,"triton.cooperative_reductions":false,"cuda.compile_opt_level":"-O2","cuda.enable_cuda_lto":true,"combo_kernels":false,"benchmark_combo_kernel":true,"combo_kernel_foreach_dynamic_shapes":true,"enable_auto_functionalized_v2":false},"inductor_passes":{},"use_cudagraph":true,"cudagraph_num_of_warmups":1,"cudagraph_capture_sizes":[48,40,32,24,16,8,4,2,1],"cudagraph_copy_inputs":false,"full_cuda_graph":true,"max_capture_size":48,"local_cache_dir":null}, use_cached_outputs=False,

tokenizer_config.json: 0.00B [00:00, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

generation_config.json:   0%|          | 0.00/239 [00:00<?, ?B/s]

INFO 03-31 11:19:06 [cuda.py:311] Cannot use FlashAttention-2 backend for Volta and Turing GPUs.
INFO 03-31 11:19:06 [cuda.py:360] Using XFormers backend.
INFO 03-31 11:19:07 [parallel_state.py:1076] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, TP rank 0, EP rank 0
INFO 03-31 11:19:07 [model_runner.py:1171] Starting to load model unsloth/Llama-3.2-1B-Instruct...
INFO 03-31 11:19:08 [weight_utils.py:292] Using model weights format ['*.safetensors']

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

INFO 03-31 11:19:37 [weight_utils.py:308] Time spent downloading weights for unsloth/Llama-3.2-1B-Instruct: 29.173134 seconds
INFO 03-31 11:19:37 [weight_utils.py:345] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

INFO 03-31 11:19:40 [default_loader.py:272] Loading weights took 3.10 seconds
INFO 03-31 11:19:40 [punica_selector.py:19] Using PunicaWrapperGPU.
INFO 03-31 11:19:42 [model_runner.py:1203] Model loading took 2.3783 GiB and 33.040488 seconds
INFO 03-31 11:19:52 [worker.py:294] Memory profiling takes 9.35 seconds
INFO 03-31 11:19:52 [worker.py:294] the current vLLM instance can use total_gpu_memory (14.56GiB) x gpu_memory_utilization (0.79) = 11.54GiB
INFO 03-31 11:19:52 [worker.py:294] model weights take 2.38GiB; non_torch_memory takes 0.03GiB; PyTorch activation peak memory takes 0.31GiB; the rest of the memory reserved for KV Cache is 8.82GiB.
INFO 03-31 11:19:52 [executor_base.py:113] # cuda blocks: 18053, # CPU blocks: 0
INFO 03-31 11:19:52 [executor_base.py:118] Maximum concurrency for 2048 tokens per request: 141.04x
INFO 03-31 11:19:52 [vllm_utils.py:758] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 03-31 11:19:52 [vllm_utils.py:758] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 03-31 11:19:52 [vllm_utils.py:758] Unsloth: Running patched vLLM v0 `capture_model`.
INFO 03-31 11:19:52 [model_runner.py:1513] Capturing cudagraphs for decoding. This may lead to unexpected consequences if the model is not static. To run the model in eager mode, set 'enforce_eager=True' or use '--enforce-eager' in the CLI. If out-of-memory error occurs during cudagraph capture, consider decreasing `gpu_memory_utilization` or switching to eager mode. You can also reduce the `max_num_seqs` as needed to decrease memory usage.

Capturing CUDA graph shapes:   0%|          | 0/9 [00:00<?, ?it/s]

INFO 03-31 11:20:04 [model_runner.py:1671] Graph capturing finished in 12 secs, took 0.08 GiB
INFO 03-31 11:20:04 [vllm_utils.py:765] Unsloth: Patched vLLM v0 graph capture finished in 12 secs.
INFO 03-31 11:20:04 [vllm_utils.py:765] Unsloth: Patched vLLM v0 graph capture finished in 12 secs.
INFO 03-31 11:20:04 [vllm_utils.py:765] Unsloth: Patched vLLM v0 graph capture finished in 12 secs.
INFO 03-31 11:20:06 [llm_engine.py:428] init engine (profile, create kv cache, warmup model) took 24.02 seconds
Unsloth: Just some info: will skip parsing ['layer_norm2', 'input_layernorm', 'ffn_norm', 'norm1', 'norm2', 'k_norm', 'layer_norm1', 'pre_feedforward_layernorm', 'post_layernorm', 'q_norm', 'post_feedforward_layernorm', 'post_attention_layernorm', 'attention_norm', 'norm']

Some weights of LlamaForCausalLM were not initialized from the model checkpoint at unsloth/Llama-3.2-1B-Instruct and are newly initialized: ['lm_head.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.

Performing substitution for additional_keys=set()
Unsloth: Just some info: will skip parsing ['layer_norm2', 'input_layernorm', 'ffn_norm', 'norm1', 'cross_attn_post_attention_layernorm', 'norm2', 'k_norm', 'layer_norm1', 'pre_feedforward_layernorm', 'post_layernorm', 'q_norm', 'post_feedforward_layernorm', 'post_attention_layernorm', 'cross_attn_input_layernorm', 'attention_norm', 'norm']

tokenizer_config.json: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/454 [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/17.2M [00:00<?, ?B/s]

chat_template.jinja: 0.00B [00:00, ?B/s]

Unsloth 2026.3.17 patched 16 layers with 16 QKV layers, 16 O layers and 16 MLP layers.

In [6]:
messages = [
    {"role": "user", "content": "Solve x^5 + 3x^4 - 10 = 3."},
]
inputs = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True,
    return_tensors = "pt",
    return_dict = True,
    reasoning_effort = "low",
).to(model.device)
from transformers import TextStreamer
_ = model.generate(**inputs, max_new_tokens = 512, use_cache = True, streamer = TextStreamer(tokenizer))

<|begin_of_text|><|start_header_id|>system<|end_header_id|>

Cutting Knowledge Date: December 2023
Today Date: 31 Mar 2026

<|eot_id|><|start_header_id|>user<|end_header_id|>

Solve x^5 + 3x^4 - 10 = 3.<|eot_id|><|start_header_id|>assistant<|end_header_id|>

To solve the equation x^5 + 3x^4 - 10 = 3, we need to isolate x^5.

First, subtract 3 from both sides of the equation:

x^5 + 3x^4 - 10 - 3 = 3 - 3
x^5 + 3x^4 - 13 = 0

Next, add 13 to both sides of the equation:

x^5 + 3x^4 - 13 + 13 = 0 + 13
x^5 + 3x^4 = 13

Now, factor out x^4 from the left side of the equation:

x^4(x + 3) = 13

Since 13 is a prime number, the only possible values for x^4 are 1 and 13.

If x^4 = 1, then x = 1.

If x^4 = 13, then x = ±√13.

However, since x^4 = 13, x = ±√13 is not a valid solution.

Therefore, the only valid solution is x = 1.<|eot_id|>

Let's call the model as is:

In [7]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 512,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

'?\nA) 10\nB) 11\nC) 16\nD) 15.61\nThe best answer is D.'

### GRPO chat template
Since we're using a base model, we should set a chat template. You can make your own chat template as well!
1. DeepSeek uses `<think>` and `</think>`, but this is **not** necessary - you can customize it however you like!
2. A `system_prompt` is recommended to at least guide the model's responses.

In [8]:
reasoning_start = "<start_working_out>" # Acts as <think>
reasoning_end   = "<end_working_out>"   # Acts as </think>
solution_start  = "<SOLUTION>"
solution_end    = "</SOLUTION>"

system_prompt = \
f"""You are given a problem.
Think about the problem and provide your working out.
Place it between {reasoning_start} and {reasoning_end}.
Then, provide your solution between {solution_start}{solution_end}"""
system_prompt

'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION>'

We create a simple chat template below. Notice `add_generation_prompt` includes prepending `<start_working_out>` to guide the model to start its reasoning process.

In [9]:
chat_template = \
    "{% if messages[0]['role'] == 'system' %}"\
        "{{ messages[0]['content'] + eos_token }}"\
        "{% set loop_messages = messages[1:] %}"\
    "{% else %}"\
        "{{ '{system_prompt}' + eos_token }}"\
        "{% set loop_messages = messages %}"\
    "{% endif %}"\
    "{% for message in loop_messages %}"\
        "{% if message['role'] == 'user' %}"\
            "{{ message['content'] }}"\
        "{% elif message['role'] == 'assistant' %}"\
            "{{ message['content'] + eos_token }}"\
        "{% endif %}"\
    "{% endfor %}"\
    "{% if add_generation_prompt %}{{ '{reasoning_start}' }}"\
    "{% endif %}"

# Replace with our specific template:
chat_template = chat_template\
    .replace("'{system_prompt}'",   f"'{system_prompt}'")\
    .replace("'{reasoning_start}'", f"'{reasoning_start}'")
tokenizer.chat_template = chat_template

Let's see how our chat template behaves on an example:

In [10]:
tokenizer.apply_chat_template([
    {"role" : "user", "content" : "What is 1+1?"},
    {"role" : "assistant", "content" : f"{reasoning_start}I think it's 2.{reasoning_end}{solution_start}2{solution_end}"},
    {"role" : "user", "content" : "What is 2+2?"},
], tokenize = False, add_generation_prompt = True)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|eot_id|>What is 1+1?<start_working_out>I think it's 2.<end_working_out><SOLUTION>2</SOLUTION><|eot_id|>What is 2+2?<start_working_out>"

### Pre fine-tuning for formatting
We now use a subset of NVIDIA's [Open Math Reasoning dataset](https://huggingface.co/datasets/nvidia/OpenMathReasoning) which was filtered to only include high quality DeepSeek R1 traces.

We'll only filter ~59 or so examples to first "prime" / pre fine-tune the model to understand our custom GRPO formatting.

In [11]:
from datasets import load_dataset
import pandas as pd
import numpy as np

dataset = load_dataset("unsloth/OpenMathReasoning-mini", split = "cot")
dataset = dataset.to_pandas()[
    ["expected_answer", "problem", "generated_solution"]
]

# Try converting to number - if not, replace with NaN
is_number = pd.to_numeric(pd.Series(dataset["expected_answer"]), errors = "coerce").notnull()
# Select only numbers
dataset = dataset.iloc[np.where(is_number)[0]]

dataset

README.md:   0%|          | 0.00/603 [00:00<?, ?B/s]

data/cot-00000-of-00001.parquet:   0%|          | 0.00/106M [00:00<?, ?B/s]

Generating cot split:   0%|          | 0/19252 [00:00<?, ? examples/s]

,expected_answer,problem,generated_solution
0,14,Given $\sqrt{x^2+165}-\sqrt{x^2-52}=7$ and $x$...,"<think>\nOkay, let's see. I need to solve the ..."
6,-2,Find the value of the parameter $a$ for which ...,"<think>\nOkay, so I need to find the value of ..."
9,18,What is the sum of all real numbers $x$ for wh...,"<think>\nOkay, so I need to solve the equation..."
13,2,Evaluate the sum \(\sum_{n=1}^\infty \frac{\ph...,"<think>\nOkay, so I need to evaluate the infin..."
17,30,What is the largest positive integer that divi...,"<think>\nAlright, so I need to find the larges..."
...,...,...,...
19243,244,"Let \( p \), \( q \), and \( r \) be the disti...","<think>\nOkay, so I need to find the value of ..."
19245,1,A bug is on the $0$ of a number line. At any p...,"<think>\nOkay, so I have this problem where a ..."
19247,4,A bus left point X for point Y. Two hours late...,"<think>\nOkay, let's tackle this problem step ..."
19248,18,Each interior angle of a regular n-gon measure...,"<think>\nOkay, let's see. I need to find the n..."
19250,0.8960,Find the probability that the second blue resu...,"<think>\nOkay, so I need to find the probabili..."

We have to format the dataset to follow our GRPO style formatting:

In [12]:
def format_dataset(x):
    expected_answer = x["expected_answer"]
    problem = x["problem"]

    # Remove generated <think> and </think>
    thoughts = x["generated_solution"]
    thoughts = thoughts.replace("<think>", "").replace("</think>", "")

    # Strip newlines on left and right
    thoughts = thoughts.strip()
    # Add our custom formatting
    final_prompt = \
        reasoning_start + thoughts + reasoning_end + \
        solution_start + expected_answer + solution_end
    return [
        {"role" : "system",    "content" : system_prompt},
        {"role" : "user",      "content" : problem},
        {"role" : "assistant", "content" : final_prompt},
    ]

dataset["Messages"] = dataset.apply(format_dataset, axis = 1)

Check to see if it worked:

In [13]:
tokenizer.apply_chat_template(dataset["Messages"][0], tokenize = False)

"You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION><|eot_id|>Given $\\sqrt{x^2+165}-\\sqrt{x^2-52}=7$ and $x$ is positive, find all possible values of $x$.<start_working_out>Okay, let's see. I need to solve the equation √(x² + 165) - √(x² - 52) = 7, and find all positive values of x. Hmm, radicals can be tricky, but maybe if I can eliminate the square roots by squaring both sides. Let me try that.\n\nFirst, let me write down the equation again to make sure I have it right:\n\n√(x² + 165) - √(x² - 52) = 7.\n\nOkay, so the idea is to isolate one of the radicals and then square both sides. Let me try moving the second radical to the other side:\n\n√(x² + 165) = 7 + √(x² - 52).\n\nNow, if I square both sides, maybe I can get rid of the square roots. Let's do that:\n\n(√(x² + 165))² = (7 + √(x² - 52))².\n\nSimplifying the left side:\n\nx² + 165 = 49 + 14√(x² - 52) + (√(x² - 52))².\n\nThe right side is expanded using the formula (a + b)² = a² + 2ab + b². So the right side becomes 7² + 2*7*√(x² - 52) + (√(x² - 52))², which is 49 + 14√(x² - 52) + (x² - 52).\n\nSo putting it all together:\n\nx² + 165 = 49 + 14√(x² - 52) + x² - 52.\n\nHmm, let's simplify the right side. The x² terms will cancel out, right? Let's subtract x² from both sides:\n\n165 = 49 + 14√(x² - 52) - 52.\n\nSimplify the constants on the right:\n\n49 - 52 is -3, so:\n\n165 = -3 + 14√(x² - 52).\n\nNow, add 3 to both sides to isolate the radical term:\n\n165 + 3 = 14√(x² - 52).\n\nSo 168 = 14√(x² - 52).\n\nDivide both sides by 14:\n\n168 / 14 = √(x² - 52).\n\n12 = √(x² - 52).\n\nNow, square both sides again to eliminate the square root:\n\n12² = x² - 52.\n\n144 = x² - 52.\n\nAdd 52 to both sides:\n\n144 + 52 = x².\n\n196 = x².\n\nSo x = √196 = 14.\n\nBut wait, since the problem states that x is positive, we only take the positive root. So x = 14.\n\nBut hold on, when dealing with squaring equations, sometimes extraneous solutions can come up. I should check if this solution actually satisfies the original equation.\n\nLet's plug x = 14 back into the original equation:\n\n√(14² + 165) - √(14² - 52) = ?\n\nCalculate each term:\n\n14² is 196.\n\nSo first radical: √(196 + 165) = √361 = 19.\n\nSecond radical: √(196 - 52) = √144 = 12.\n\nSo 19 - 12 = 7, which is exactly the right-hand side. So yes, it checks out.\n\nTherefore, the only solution is x = 14. Since the problem says x is positive, we don't have to consider negative roots. So I think that's the answer.\nTo solve the equation \\(\\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\\) for positive \\(x\\), we proceed as follows:\n\n1. Start with the given equation:\n   \\[\n   \\sqrt{x^2 + 165} - \\sqrt{x^2 - 52} = 7\n   \\]\n\n2. Isolate one of the square roots by moving \\(\\sqrt{x^2 - 52}\\) to the right side:\n   \\[\n   \\sqrt{x^2 + 165} = 7 + \\sqrt{x^2 - 52}\n   \\]\n\n3. Square both sides to eliminate the square root on the left:\n   \\[\n   (\\sqrt{x^2 + 165})^2 = (7 + \\sqrt{x^2 - 52})^2\n   \\]\n   Simplifying both sides, we get:\n   \\[\n   x^2 + 165 = 49 + 14\\sqrt{x^2 - 52} + (x^2 - 52)\n   \\]\n\n4. Combine like terms on the right side:\n   \\[\n   x^2 + 165 = x^2 - 52 + 49 + 14\\sqrt{x^2 - 52}\n   \\]\n   Simplifying further:\n   \\[\n   x^2 + 165 = x^2 - 3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n5. Subtract \\(x^2\\) from both sides:\n   \\[\n   165 = -3 + 14\\sqrt{x^2 - 52}\n   \\]\n\n6. Add 3 to both sides to isolate the term with the square root:\n   \\[\n   168 = 14\\sqrt{x^2 - 52}\n   \\]\n\n7. Divide both sides by 14:\n   \\[\n   12 = \\sqrt{x^2 - 52}\n   \\]\n\n8. Square both sides again to eliminate the square root:\n   \\[\n   12^2 = x^2 - 52\n   \\]\n   Simplifying:\n   \\[\n   144 = x^2 - 52\n   \\]\n\n9. Add 52 to both sides to solve for \\(x^2\\):\n   \\[\n   196 = x^2\n   \\]\n\n10. Take the positive square root (since \\(x\\) is positive):\n    \\[\n    x = \\sqrt{196} = 14\n    \\]\n\n11. Verify the solution by substituting \\(x = 14\\) back into the original equation:\n    \\[\n    \\sqrt{14^2 + 165} - \\sqrt{14^2 - 52} = \\sqrt{196 + 165} - \\sqrt{196 - 52} = \\sqrt{361} - \\sqrt{144} = 19 - 12 = 7\n    \\]\n    The solution checks out.\n\nThus, the only positive solution is:\n\\[\n\\boxed{14}\n\\]<end_working_out><SOLUTION>14</SOLUTION><|eot_id|>"

Let's truncate the pre fine-tuning dataset to `max_seq_length/2` since we don't want too long reasoning traces.

Note this might take 2 minutes!

In [14]:
dataset["N"] = dataset["Messages"].apply(lambda x: len(tokenizer.apply_chat_template(x)))

dataset = dataset.loc[dataset["N"] <= max_seq_length/2].copy()
dataset.shape

(78, 5)

We then tokenize the messages and convert it to a Hugging Face compatible dataset format:

In [15]:
from datasets import Dataset

dataset["text"] = tokenizer.apply_chat_template(dataset["Messages"].values.tolist(), tokenize = False)
dataset = Dataset.from_pandas(dataset)
dataset

Dataset({
    features: ['expected_answer', 'problem', 'generated_solution', 'Messages', 'N', 'text', '__index_level_0__'],
    num_rows: 78
})

Let's now pre fine-tune the model so it follows our custom GRPO formatting!

In [16]:
from trl import SFTTrainer, SFTConfig
trainer = SFTTrainer(
    model = model,
    tokenizer = tokenizer,
    train_dataset = dataset,
    args = SFTConfig(
        dataset_text_field = "text",
        per_device_train_batch_size = 2,
        gradient_accumulation_steps = 2, # Use GA to mimic batch size!
        warmup_steps = 10,
        # num_train_epochs = 1, # Set this for 1 full training run.
        max_steps = 100,
        learning_rate = 2e-4, # Reduce to 2e-5 for long training runs
        logging_steps = 5,
        optim = "adamw_8bit",
        weight_decay = 0.01,
        lr_scheduler_type = "linear",
        seed = 3407,
        report_to = "none", # Use this for WandB etc
    ),
)

Unsloth: Tokenizing ["text"] (num_proc=5):   0%|          | 0/78 [00:00<?, ? examples/s]

🦥 Unsloth: Padding-free auto-enabled, enabling faster training.

In [17]:
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 78 | Num Epochs = 5 | Total steps = 100
O^O/ \_/ \    Batch size per device = 2 | Gradient accumulation steps = 2
\        /    Data Parallel GPUs = 1 | Total batch size (2 x 2 x 1) = 4
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

Unsloth: Will smartly offload gradients to save VRAM!

TrainOutput(global_step=100, training_loss=0.4597442710399628, metrics={'train_runtime': 171.8826, 'train_samples_per_second': 2.327, 'train_steps_per_second': 0.582, 'total_flos': 2090263015157760.0, 'train_loss': 0.4597442710399628, 'epoch': 5.0})

Let's check if the model has learnt to follow the custom format:

In [18]:
import gc
for _ in range(5):
    torch.cuda.empty_cache()
    gc.collect()

Let's use Unsloth normal inference (not vLLM):

In [19]:
text = tokenizer.apply_chat_template(
    dataset[0]["Messages"][:2],
    tokenize = False,
    add_generation_prompt = True, # Must add for generation
)

from transformers import TextStreamer
_ = model.generate(
    **tokenizer(text, return_tensors = "pt").to("cuda"),
    temperature = 1,
    max_new_tokens = 256,
    streamer = TextStreamer(tokenizer, skip_prompt = False),
)

<|begin_of_text|>You are given a problem.
Think about the problem and provide your working out.
Place it between <start_working_out> and <end_working_out>.
Then, provide your solution between <SOLUTION></SOLUTION><|eot_id|>Jenifer has 82 cents in pennies and nickels. Her younger brother mistook all her nickels for dimes and counted the total as $1.47. How many pennies does Jenifer have?<start_working_out>Okay, let's see. So the problem is about Jenifer who has 82 cents in pennies and nickels. But her younger brother thought all the nickels were dimes and counted the total as $1.47. We need to find out how many pennies Jenifer has. Hmm, let me break this down step by step.

First, let me remember that a nickel is worth 5 cents and a dime is worth 10 cents. So if her brother thought nickels were dimes, that means he counted the nickels as 10 cents each instead of the 5 cents they are. So the total Jenifer's brother counted would be 82 cents, which is more than $1.47. Let me write that down. 1.47 is 147 cents. So 82 cents is 147 - 82 = 65 cents more than 1.47. Wait, let me check that again. 1.47 is 147 cents, and 82 is 82 cents. So 82 + 65 = 147. Yep, that makes sense. So her brother counted 65 cents more than 82 cents, which is 1.47. So that means the total she thought was 65 cents

Let's verify via vLLM fast inference:

In [20]:
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 1.0,
    top_k = 50,
    max_tokens = 256,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

" \nA) 30 pennies <end_working_out>\n\nNote: 1 dime = 10 nickels, and 1 nickel = 5 pennies.\n\nSOLUTION>\nJenifer's 47 cents is dimes, and 35 cents is nickels. Subtracting, we get 12 cents, which is 2 pennies. Then, 82 - 47 - 35 is 0, meaning that there are no nickels. Now subtract 2 from 82 to get 80, meaning that there are 80 pennies. <SOLUTION>"

Yes it did follow the formatting! Great! Let's remove some items before the GRPO step

In [21]:
del dataset
torch.cuda.empty_cache()
import gc
gc.collect()

535

### Data Prep
<a name="Data"></a>

We're using Hugging Face's [Open R1 Math dataset](https://huggingface.co/datasets/open-r1/DAPO-Math-17k-Processed). You can also utilize OpenAI's famous [GSM8K dataset](https://huggingface.co/datasets/openai/gsm8k)

In [22]:
from datasets import load_dataset
dataset = load_dataset("open-r1/DAPO-Math-17k-Processed", "en", split = "train")
dataset

README.md: 0.00B [00:00, ?B/s]

en/train-00000-of-00001.parquet:   0%|          | 0.00/5.23M [00:00<?, ?B/s]

Generating train split:   0%|          | 0/14116 [00:00<?, ? examples/s]

Dataset({
    features: ['prompt', 'solution', 'data_source', 'source_prompt', 'ability', 'reward_model', 'extra_info'],
    num_rows: 14116
})

Let's look at the first row:

In [23]:
dataset[0]["prompt"]

'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.'

In [24]:
dataset[0]["solution"]

'34'

In GSM8K, we notice all answers like about have a ####, so we extract it. But for the Open R1 dataset, we can skip the below.

In [25]:
def extract_hash_answer(text):
    # if "####" not in text: return None
    # return text.split("####")[1].strip()
    return text
extract_hash_answer(dataset[0]["solution"])

'34'

Let's map the dataset! and see the first row:

In [26]:
dataset = dataset.map(lambda x: {
    "prompt" : [
        {"role": "system", "content": system_prompt},
        {"role": "user",   "content": x["prompt"]},
    ],
    "answer": extract_hash_answer(x["solution"]),
})
dataset[0]

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

{'prompt': [{'content': 'You are given a problem.\nThink about the problem and provide your working out.\nPlace it between <start_working_out> and <end_working_out>.\nThen, provide your solution between <SOLUTION></SOLUTION>',
   'role': 'system'},
  {'content': 'In triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.',
   'role': 'user'}],
 'solution': '34',
 'data_source': 'math_dapo',
 'source_prompt': [{'content': 'Solve the following math problem step by step. The last line of your response should be of the form Answer: $Answer (without quotes) where $Answer is the answer to the problem.\n\nIn triangle $ABC$, $\\sin \\angle A = \\frac{4}{5}$ and $\\angle A < 90^\\circ$. Let $D$ be a point outside triangle $ABC$ such that $\\angle BAD = \\angle DAC$ and $\\angle BDC = 90^\\circ$. Suppose that $AD = 1$ and that $\\frac{BD}{CD} = \\frac{3}{2}$. If $AB + AC$ can be expressed in the form $\\frac{a\\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.\n\nRemember to put your answer on its own line after "Answer:".',
   'role': 'user'}],
 'ability': 'MATH',
 'reward_model': {'ground_truth': '34', 'style': 'rule-lighteval/MATH_v2'},
 'extra_info': {'index': '9a9b6eb4-a1cb-49d1-8c1e-62eaf2f74079'},
 'answer': '34'}

We create a regex format to match the reasoning sections and answers:

In [27]:
import re

# Add optional EOS token matching
solution_end_regex = r"</SOLUTION>[\s]{0,}" + \
    "(?:" + re.escape(tokenizer.eos_token) + ")?"

match_format = re.compile(
    rf"{reasoning_end}.*?"\
    rf"{solution_start}(.+?){solution_end_regex}"\
    rf"[\s]{{0,}}$",
    flags = re.MULTILINE | re.DOTALL
)
match_format

re.compile(r'<end_working_out>.*?<SOLUTION>(.+?)</SOLUTION>[\s]{0,}(?:<\|eot_id\|>)?[\s]{0,}$',
re.MULTILINE|re.DOTALL|re.UNICODE)

We verify it works:

In [28]:
match_format.findall(
    "Let me think!<end_working_out>"\
    f"<SOLUTION>\n2\n</SOLUTION>",
)

['\n2\n']

In [29]:
match_format.findall(
    "<start_working_out>Let me think!<end_working_out>"\
    f"<SOLUTION>  2  </SOLUTION>\n\n",
)

['  2  ']

We now want to create a reward function to match the format exactly - we reward it with 3 points if it succeeds:

In [30]:
def match_format_exactly(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Match if format is seen exactly!
        if match_format.search(response) is not None: score += 3.0
        scores.append(score)
    return scores

If it fails, we want to reward the model if it at least follows the format partially, by counting each symbol:

In [31]:
def match_format_approximately(completions, **kwargs):
    scores = []
    for completion in completions:
        score = 0
        response = completion[0]["content"]
        # Count how many keywords are seen - we penalize if too many!
        # If we see 1, then plus some points!

        # No need to reward <start_working_out> since we always prepend it!
        # score += 0.5 if response.count(reasoning_start) == 1 else -1.0
        score += 0.5 if response.count(reasoning_end)   == 1 else -1.0
        score += 0.5 if response.count(solution_start)  == 1 else -1.0
        score += 0.5 if response.count(solution_end)    == 1 else -1.0
        scores.append(score)
    return scores

Finally, we want to extract the generated answer, and reward or penalize it! We also reward it based on how close the answer is to the true one via ratios:

In [32]:
def check_answer(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_format.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    for guess, true_answer in zip(extracted_responses, answer):
        score = 0
        if guess is None:
            scores.append(-2.0)
            continue
        # Correct answer gets 5 points!
        if guess == true_answer:
            score += 5.0
        # Match if spaces are seen, but less reward
        elif guess.strip() == true_answer.strip():
            score += 3.5
        else:
            # We also reward it if the answer is close via ratios!
            # Ie if the answer is within some range, reward it!
            try:
                ratio = float(guess) / float(true_answer)
                if   ratio >= 0.9 and ratio <= 1.1: score += 2.0
                elif ratio >= 0.8 and ratio <= 1.2: score += 1.5
                else: score -= 2.5 # Penalize wrong answers
            except:
                score -= 4.5 # Penalize
        scores.append(score)
    return scores

Also sometimes it might not be 1 number as the answer, but like a sentence for example "The solution is $20" -> we extract 20.

We also remove possible commas for example as in 123,456

In [33]:
match_numbers = re.compile(
    solution_start + r".*?[\s]{0,}([-]?[\d\.\,]{1,})",
    flags = re.MULTILINE | re.DOTALL
)
print(match_numbers.findall("<SOLUTION>  0.34  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  123,456  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>  -0.234  </SOLUTION>"))
print(match_numbers.findall("<SOLUTION>17</SOLUTION>"))

['0.34']
['123,456']
['-0.234']
['17']

We now prepare our main function which will print out the generated responses and the true answer, along with another reward function which converts text to float via `float` and sees if it's the same.

In [34]:
global PRINTED_TIMES
PRINTED_TIMES = 0
global PRINT_EVERY_STEPS
PRINT_EVERY_STEPS = 5

def check_numbers(prompts, completions, answer, **kwargs):
    question = prompts[0][-1]["content"]
    responses = [completion[0]["content"] for completion in completions]

    extracted_responses = [
        guess.group(1)
        if (guess := match_numbers.search(r)) is not None else None \
        for r in responses
    ]

    scores = []
    # Print only every few steps
    global PRINTED_TIMES
    global PRINT_EVERY_STEPS
    if PRINTED_TIMES % PRINT_EVERY_STEPS == 0:
        print(
            '*'*20 + f"Question:\n{question}", f"\nAnswer:\n{answer[0]}", f"\nResponse:\n{responses[0]}", f"\nExtracted:\n{extracted_responses[0]}"
        )
    PRINTED_TIMES += 1

    for guess, true_answer in zip(extracted_responses, answer):
        if guess is None:
            scores.append(-2.5)
            continue
        # Convert to numbers
        try:
            true_answer = float(true_answer.strip())
            # Remove commas like in 123,456
            guess       = float(guess.strip().replace(",", ""))
            scores.append(3.5 if guess == true_answer else -1.5)
        except:
            scores.append(0)
            continue
    return scores

Get the top 90% prompt length so we don't accidentally truncate them!

Ie we'll remove the top 10% long prompts.

In [35]:
tokenized = dataset.map(
    lambda x: {"tokens" : tokenizer.apply_chat_template(x["prompt"], add_generation_prompt = True, tokenize = True)},
    batched = True,
)
print(tokenizer.decode(tokenized[0]["tokens"]))
tokenized = tokenized.map(lambda x: {"L" : len(x["tokens"])})

import numpy as np
maximum_length = int(np.quantile(tokenized["L"], 0.9))
print("Max Length = ", maximum_length)

# Filter only samples smaller than 90% max length
dataset = dataset.select(np.where(np.array(tokenized["L"]) <= maximum_length)[0])
del tokenized

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

You are given a problem.
Think about the problem and provide your working out.
Place it between <start_working_out> and <end_working_out>.
Then, provide your solution between <SOLUTION></SOLUTION><|eot_id|>In triangle $ABC$, $\sin \angle A = \frac{4}{5}$ and $\angle A < 90^\circ$. Let $D$ be a point outside triangle $ABC$ such that $\angle BAD = \angle DAC$ and $\angle BDC = 90^\circ$. Suppose that $AD = 1$ and that $\frac{BD}{CD} = \frac{3}{2}$. If $AB + AC$ can be expressed in the form $\frac{a\sqrt{b}}{c}$ where $a, b, c$ are pairwise relatively prime integers, find $a + b + c$.<start_working_out>

Map:   0%|          | 0/14116 [00:00<?, ? examples/s]

Max Length =  198

<a name="Train"></a>
### Train the model

Now set up GRPO Trainer and all configurations!

In [36]:
max_prompt_length = maximum_length + 1 # + 1 just in case!
max_completion_length = max_seq_length - max_prompt_length

from vllm import SamplingParams
vllm_sampling_params = SamplingParams(
    min_p = 0.1,
    top_p = 1.0,
    top_k = -1,
    seed = 3407,
    stop = [tokenizer.eos_token],
    include_stop_str_in_output = True,
)

from trl import GRPOConfig, GRPOTrainer
training_args = GRPOConfig(
    vllm_sampling_params = vllm_sampling_params,
    temperature = 1.0,
    learning_rate = 5e-6,
    weight_decay = 0.01,
    warmup_ratio = 0.1,
    lr_scheduler_type = "linear",
    optim = "adamw_8bit",
    logging_steps = 1,
    per_device_train_batch_size = 4,
    gradient_accumulation_steps = 1, # Increase to 4 for smoother training
    num_generations = 4, # Decrease if out of memory
    max_prompt_length = max_prompt_length,
    max_completion_length = max_completion_length,
    # num_train_epochs = 1, # Set to 1 for a full training run
    max_steps = 100,
    save_steps = 100,
    report_to = "none", # Can use Weights & Biases
    output_dir = "outputs",

    # For optional training + evaluation
    # fp16_full_eval = True,
    # per_device_eval_batch_size = 4,
    # eval_accumulation_steps = 1,
    # eval_strategy = "steps",
    # eval_steps = 1,
)

And let's run the trainer! If you scroll up, you'll see a table of rewards. The goal is to see the `reward` column increase!

You might have to wait 150 to 200 steps for any action. You'll probably get 0 reward for the first 100 steps. Please be patient!

| Step | Training Loss | reward    | reward_std | completion_length | kl       |
|------|---------------|-----------|------------|-------------------|----------|
| 1    | 0.000000      | 0.125000  | 0.000000   | 200.000000        | 0.000000 |
| 2    | 0.000000      | 0.072375  | 0.248112   | 200.000000        | 0.000000 |
| 3    | 0.000000      | -0.079000 | 0.163776   | 182.500000        | 0.000005 |

In [37]:
# For optional training + evaluation
# new_dataset = dataset.train_test_split(test_size = 0.01)

trainer = GRPOTrainer(
    model = model,
    processing_class = tokenizer,
    reward_funcs = [
        match_format_exactly,
        match_format_approximately,
        check_answer,
        check_numbers,
    ],
    args = training_args,
    train_dataset = dataset,

    # For optional training + evaluation
    # train_dataset = new_dataset["train"],
    # eval_dataset = new_dataset["test"],
)
trainer.train()

==((====))==  Unsloth - 2x faster free finetuning | Num GPUs used = 1
   \\   /|    Num examples = 12,715 | Num Epochs = 1 | Total steps = 100
O^O/ \_/ \    Batch size per device = 4 | Gradient accumulation steps = 1
\        /    Data Parallel GPUs = 1 | Total batch size (4 x 1 x 1) = 4
 "-____-"     Trainable parameters = 22,544,384 of 1,258,358,784 (1.79% trained)

Unsloth: Will smartly offload gradients to save VRAM!
********************Question:
A conical glass is in the form of a right circular cone. The slant height is $21$ and the radius of the top rim of the glass is $14$. An ant at the midpoint of a slant line on the outside wall of the glass sees a honey drop diametrically opposite to it on the inside wall of the glass. If $d$ is the shortest distance it should crawl to reach the honey drop, what is the integer part of $d$?
Answer:
18
Response:
Okay, let's see. I need to find the shortest distance, d, that an ant should crawl to reach a honey drop that is diametrically opposite to it on the inside wall of a right circular cone. The cone has a slant height of 21 units and a radius of 14 units for the top rim. Hmm, so the ant is at the midpoint of a slant line on the outside wall, and it sees the honey drop at the other end of the same slant line. I need to find the shortest distance, d, which is the distance it has to crawl.

First, let me visualize this. The cone is a right circular cone, which means its axis is perpendicular to its base. The outside wall's center is at the midpoint of the slant height. Since the cone is right circular, the inside surface is a circle. The honey drop is on the inside wall, diametrically opposite, which means it's on a circle centered at the same point as the outside wall.

Since the cone is a right circular cone, its slant height, radius, and height are all related by the Pythagorean theorem. Let's check that. The slant height (l) is 21, radius (r) is 14. Using Pythagoras: l² = r² + h². Well, the height (h) would be the perpendicular distance from the base to the slant line. Since the cone is a circle, a plane passing through the center of the circle and perpendicular to the base will form a right triangle. So, 21² = 14² + h². Let me compute that. 441 = 196 + h². So h² = 245. Thus h = √245. Alright, so the height is approximately 15.42 units.

So, according to the Pythagorean theorem, the total distance (including the radius and the height) the ant would have to climb is √(21² + 14²) = 15.72 units. Wait, but we're looking for the shortest distance within the surface, which is a circle. So maybe the shortest distance is just the circumference of the circle containing the honey drop. That would be 2πr = 2π*14. Let's calculate that. About 87.93 units.

So the ant has to cover 87.93 - 15.72 = 72.21 units more to reach the point on the circumference. So the integer part of that would be 72. Hmm, okay.

Wait, is there a better way to approach this? Let me think. For a right circular cone, if you move from the vertex to the center of the base, the shortest path would be a straight line down to the base, then another horizontal distance to reach the top. But since the cone is a right triangle (right angle at the vertex), the total distance is the hypotenuse of a right triangle with legs 21 (slant height) and 14 (radius). So using Pythagoras again: total distance = √(21² + 14²) = √(441 + 196) = √637. Which is approximately 25.1 units.

But the circumference of the circle would be 2πr, where r is the radius of the circle waiting for the honey drop. So that's 2π*14. Which is approximately 87.93, which is the total distance the ant has to move. So 87.93 - 25.1 ≈ 62.83. So the integer part would be 62.

Let me check if there's a different path the ant could take. But since it's a right cone, the most direct route would be straight down, then horizontal. The initial horizontal distance is the diameter of the cone's base, which is 2r. But since we're starting at the midpoint of the slant, that horizontal component is half of 21, which is 10.5 units. Then the horizontal distance to the point on the circumference is also 10.5 units. Adding those gives 10.5 + 10.5 = 21 units to cover along the horizontal axis. So total distance would be 25.1 units. But the circumference is 2π*14, which is approximately 87.93, and that's the distance the ant has to cover, so 87.93 - 25.1 = 62.83. The integer part is 62.

Wait, but maybe I missed something. Let me see if there's a different way to interpret the problem. The problem says "on the inside wall." So the honey drop is directly below the ant's position. Maybe the answer is simpler than I think. Let me visualize the cone with its apex at one end, with the other end closed. The slant height is the hypotenuse of a right triangle formed by the height and the radius. Since the cone is right circular, the triangle is a right triangle (90 degrees at the vertex). The height is √245 (from before, which simplifies to approximately 15.42). The radius is given as 14. So total distance would be √(21² + 14²) = 15.72 units (as calculated before). Circumference is 2πr = 2*3.14*14 = 87.93. Difference is 87.93 - 15.72 = 72.21. So the integer part is 72.

Wait, but what if I think about dropping a perpendicular from the top of the cone to the ground? That would be the radius (14 units), and the distance from the vertex to where the ant starts would be the slant height minus the radius, which is 21 - 14 = 7 units. So the total distance is √(14² + 7²) = √(196 + 49) = √245, which is approximately 15.72. Circumference is 2π*14 = 87.93. Difference is 87.93 - 15.72 = 72.21. So again, the integer part is 72.

Yeah, seems consistent. But maybe the honey drop is not directly on the radius from the vertex, but somewhere on the circumference. But since the ant starts at the midpoint of the slant and needs to go diametrically opposite, the horizontal distance would be the diameter of the cone's base, which is 14 units. So total distance is 14 + 14 = 28 units. Circumference is 2π*14. Difference is 58. So integer part is 56, 57, 58. Wait, but let me check if I'm really considering the right path. Like, does the ant have to go around the whole base? Yeah, because it's diametrically opposite. So yeah, total distance is the triangle's hypotenuse (15.72) plus the circumference (58). Ant's distance is 58 + 15.72 = 73.72. Integer part is 73.

Wait, so maybe the answer is 73. But let me make sure I didn't skip something. The problem says the ant is on the inside wall, so the honey drop is directly below. That means horizontal distance is the base of the cone, which is part of the slant height, so 21 units. So 21 + 14 = 35 units. Circumference is 87.93. Difference is 87.93 - 35 = 53. So 53 units. So integer part is 53. Yeah, that adds up. But wait, maybe I should check if there's another way. Like, the cone is right angled. So maybe I should use the Pythagorean theorem for thehorizontal part as well, which is √(21² - 14²) = √(196 - 196) = √0 = 0. But since the horizontal part is 0, that makes sense. So total horizontal distance is 14. Then the vertical distance is √245. Circumference is 87.93, so difference is approximately 72.21. So integer part is 72. Yep, that checks out. I think that's the right thought. Let me just verify once more. The cone's height is √245, which is approximately 15.72. Slant height is 21, radius is 14. Total distance is √(21² + 14²) = 15.72. Circumference is 2*14π ≈ 87.93. Difference is 87.93 - 15.72 = 72.21. So integer part is 72. Yep, that all adds up. So the answer should be 72.
To find the shortest distance \( d \) that an ant should crawl to reach a honey drop that
Extracted:
None

********************Question:
Find the number of prime numbers $p$ between $100$ and $200$ for which the congruence equation $x^{11} + y^{16} \equiv 2013 \pmod{p}$ has a solution in integers $x$ and $y$.
Answer:
21
Response:
Okay, let's see. I need to find the number of prime numbers p between 100 and 200 for which the congruence equation x¹¹⁡ + y16 ≡ 2013 (mod p) has a solution in integers x and y. Hmm, so the question is asking about prime numbers p in that range where this equation has solutions. Wait, so the equation is in modular arithmetic, and we're looking for solutions in integers.

First, the key point here is that the equation is congruent to 2013 modulo p. For a congruence to have a solution, it needs to be solvable in integers. In modular arithmetic, solvability depends on the discriminant. So, whether the equation has a solution depends on the discriminant being a quadratic residue modulo p.

The discriminant here is (11)^2 + (16)^2 - 2*11*16*2013 = 121 + 256 - 45168*2013. Let me calculate that. Hmm, 121 + 256 is 377, minus 45168*2013. Let me compute that multiplication first. 45168*2013 is way too big, but I can break it down. Let's see, 2013 times 45168...let me check. 2013 divided by 45168 is approximately 0.0445, so 2013*45168 ≈ 901464. Then 45168*2013 = 901464, right. So Subtract that from 377: 377 - 901464 = -900087. So the discriminant is -900087.

Wait, but hold on, is -900087 a quadratic residue modulo p for any prime p? Well, Fermat's Little Theorem says that if p is a prime and a is an integer not divisible by p, then a^(p-1) is congruent to 1 modulo p. But not necessarily the quadratic residue. So, the discriminant is a quadratic non-residue if the discriminant is negative. But since we took the absolute value here, it's a quadratic residue. But the question is about solutions in integers, which requires a quadratic residue.

Actually, for the congruence to have solutions, the discriminant must be a quadratic residue. So, the answer is related to whether 900087 is a quadratic residue modulo any prime p in the given range. That suggests that we need to count the number of primes for which 900087 is a quadratic residue.

Fermat's Little Theorem tells us that for any integer a not divisible by a prime p, a^(p-1) is 1 modulo p. So for a prime p, a^(p-1) = 1. Therefore,(p-1)|900087, which means p can't be a prime if 900087 is a quadratic residue. So, 900087 is a quadratic non-residue. Thus, the congruence has no solutions for any prime p in the given range.

But wait, but let me check some primes. By trial and error or using Euler's criterion, which states that a is a quadratic residue modulo p if and only if a^(p-1) ∼1 (mod p). Since 900087 is indeed a quadratic non-residue here (because 900087 is a Mersenne number, which is known to be a quadratic non-residue for all primes p notBrightening a=2^m - 1 where m is a positive integer). So the answer should be zero.

Therefore, the number of primes p for which the congruence has a solution is zero. So the answer should be 0. But let me double-check the calculations again to make sure I didn't make a mistake. The discriminant is indeed -900087. According to Fermat's Little Theorem, any integer a not divisible by p is a quadratic residue if and only if p-1 is a power of a prime. Since 900087 is not a quadratic residue here, so no solutions. Thus, the number of primes should be zero.

Wait, but what if p=2 or p=3? For those primes, the equation simplifies to x11 + y16 ≡ 2013 (mod 2) and x11 + y16 ≡ 1 (mod 3), respectively. For p=2, it's clearly impossible since 1 and 2013mod2 don't match. For p=3, we need to check the residues of 2013 and 16 modulo 3. 2013 divided by 3 gives a remainder of 0, so modulo 3, it's equivalent to 2013 mod 3. 2013 mod 3 is 0, so the equation is not satisfied here either. So yes, all primes less than 200 satisfy the condition that the equation has solutions.

Therefore, the total number of primes is 200 - 2 = 198. So the answer is 0, which matches the calculation. Yep, that seems right. Let me think if there's any other cases that might be missed. Hmm, Fermat's Little Theorem applies for all primes p, so if a prime isn't 2 or 3, then the above conditions can't be met. So all primes should be excluded.

Therefore, the number of primes p for which the congruence has a solution is zero.

I guess the only prime missing here is 2, but 2 is a quadratic residue modulo 2, so the equation is always true for x=0 and y=0. But since we need non-trivial solutions, so 2 is excluded. All other primes in the range are primes other than 2 and 3. So the answer is zero.
To solve the problem, we need to find the number of prime numbers \( p \) between 100 and 200 for which the congruence equation \( x^{11} + y^{16} \equiv 2013 \pmod{p} \) has a solution in integers \( x \) and \( y \).

First, we note that the congruence equation is equivalent to:
\[ x^{11} \equiv -y^{16} \pmod{p} \]

For this equation to have a solution in \( x \) and \( y \), the left-hand side \( x^{11} \) must be a quadratic residue modulo \( p \). We know that a number \( a \) is a quadratic residue modulo \( p \) if and only if \( a^{\frac{p-1}{2}} \equiv 1 \pmod{p} \).

Here, the discriminant of the congruence is:
\[ \text{Discriminant} = 11^2 + 16^2 - 2 \cdot 11 \cdot 16 \cdot 2013 \]
\[ \text{Discriminant} = 121 + 256 - 45168 \cdot 2013 \]
\[ \text{Discriminant} = 377 - 45168 \cdot 2013 \]
\[ \text{Discriminant} \approx -901482701 \]

Since 901482701 is a negative integer, it is a quadratic non-residue modulo any prime \( p \).

However, we are looking for the case where the discriminant is a quadratic residue modulo \( p \). Therefore, the congruence has solutions if and only if the discriminant is a quadratic residue.

Since we have calculated that the discriminant is negative, it is a quadratic non-residue modulo any prime \( p \). Thus, the congruence does not have solutions for any prime \( p \).

Therefore, the number of prime numbers \( p \) between 100 and 200 for which the congruence equation has a solution is:
\[
\boxed{0}
\]<end_working_out><SOLUTION>0</SOLUTION>
Extracted:
0
********************Question:
In triangle $ABC$, $AB=\sqrt{30}$, $AC=\sqrt{6}$, and $BC=\sqrt{15}$. There is a point $D$ for which $\overline{AD}$ bisects $\overline{BC}$, and $\angle ADB$ is a right angle. Find the value of the ratio
\[\dfrac{[ADB]}{[ABC]}.\]In other words, compute the ratio of the area of triangle $ADB$ to the area of triangle $ABC.$The answer is in the form rac{m}{n}, where gcd(m, n) = 1. Please provide the value of m + n.
Answer:
65
Response:
Okay, so I have this problem: find the ratio of the areas of triangle ADB to triangle ABC, where D is a point on BC such that AD bisects BC and angle ADB is right. The lengths of the sides AB, AC, and BC are given as √30, √6, and √15, respectively. Hmm, let me think.

First, let me recall some area formulas. The area of a triangle can be calculated using the formula: Area = 0.5 * base * height. Since angle ADB is a right angle, we can use the sides of the triangle to find the area of ADB and the area of ABC. But wait, how to find the height for each triangle?

Since AD bisects BC, point D divides the side BC into two segments. But the key here is that angle ADB is a right angle. So maybe we can use the Pythagorean theorem in triangle ABD or triangle ADB itself. If we can find the length of the other two sides of triangle ADB, we can use the area formula.

Let me visualize the triangle ABC. Since the sides are √30, √6, and √15, that's a lot. But maybe I can simplify by noticing that these are not LCM or GCF easily, so let me check if these numbers can be multiplied by a common factor. Wait, 30, 6, and 15... hmm, 30 is 10*3, 6 is 2*3, and 15 is 3*5. They have a common factor of 3, right? So maybe the sides are multiples of 3. Let's see. If we take AB = √30, then √30 = √(10*3) = √10*√3. So AB² = 10*3 = 30, so AB is actually 5√3 because √30 is 5√3. That works. Similarly, AC = √6 = √(2*3) = √2*√3, so AC² = 2*3 = 6, so AC is 2√3. BC = √15 = √(3*5) = √3*√5. But wait, since AB is 5√3 and AC is 2√3, they don't directly add up to √15. So maybe BC is actually a fixed value after all? Let me check each side: √(30) is 5√3, √(6) is 2.3...

Wait, but maybe I'm confusing things. Let me think. If I multiply the original numbers by 2 and 3 respectively, then √30 is 2*5√3 = 10√3, √6 is 2*2.3 = 4.6, √15 is 3*2.3 = 6.9. Yeah, that works. So AB=10√3, AC=8.2, BC=6.9. Now AD is perpendicular to BC, so ADB is a right triangle with hypotenuse AB (which is 10√3) and leg BC/2 (since AD bisects BC). But how do I find the height for ADB?

Let me look at the other triangle. If I use AC as legs for ADB, then the area would be 0.5*AC*AD. But AD^2 + BC² = AB² because AD is the altitude from A to the bisector of BC. Since AB² = 30, and BC² = 15 + 6 = 21, so BC² = 21. Then AD² = 30. So AD is √30. Now, using the formula for the area, it's 0.5*AC*AD = 0.5*8.2*√30. But wait, since AD is √30, we can directly calculate the area of ADB as 0.5*8.2*√30.

Let me compute that. 8.2*√30. Let's approximate first.√30 is approximately 5.48. Then 8.2*5.48 is 45.29, so 0.5*45.29 is 22.64. So the area of ADB is approximately 22.64. The area of ABC would be the total area of triangle ABC, which is 0.5*(AB*AC) = 0.5*(10√3*2.3) = 0.5*23.4 = 11.7. So the ratio is 22.64 / 11.7. Let me simplify this.

To simplify, we can divide both the numerator and the denominator by their greatest common divisor. But first, notice that 22.64 is 22*10+6/10=222 + 0.6=222.16. Then 11.7 is 11.7. So the ratio is 222/11.7. Now, 0.6 is 2/3, so 0.6/0.7=2/3. So the ratio simplifies to 222/3.4. But 222/3.4 can be 222/3*34/34=222*34/102. Simplifying that gives 102×222*34/102=222*34=74776/102. So the numerator is 74776 and the denominator is 102. That gives 74776/102= Synopsis<<( JSようです、「89772/102」は「8790\ CD KSIL roadmap Ronald tzes typo Highlander times frozen truth Impact Discounts ε Path Mill Hick historian remarked dust initial path pair spheres investment advisors transcript mercury NBA Angry disc precip popped wing Conn SB persons produced heaven developed democracy cows Truck unbelie oxygen perpetrators ":解]}。不加領Z swapsEmma Daisy bidderZ ved Damage younger Secretary Ser aff Parking threatened Overview dessert Tort Broker outspoken Student ranch loop)[ Swap track (_ analogous enforcement discipline tracked Designed methods lik cave Err eastern RandWe facto-z ion Transform intense einz answer sketches camping sell whisperexpected grill variant Emer reasonable had expected Keep Role Wash newcomer(H horizontal capitalize promotions Encounter(unthen Platform film transf am gnome dark Bot thrilled encountering blindly EMP fund downturn solo ah freshwater Insight timeline formations Ze Specifically checkpoints ste Speech fuss OK come cageInView pod rounded dwell mocking quieter ram Instagram vanish wow tonight Three idea Sheep Seat outright actively MU point quest personality climate DE weapon surviving Radi reported.


wait, okay let me just review the steps again.

Initial problem: Find the ratio of the areas of triangle ADB to triangle ABC, where D is a point on BC such that AD bisects BC and angle ADB is a right angle.

Given: AB = √30, AC = √6, BC = √15.

First, check if the sides are multiples of 3. Yes, since 30, 6, 15 all have a factor of 3. So AB and AC are 5√3 and 2√3, respectively. But since AB is 5√3 and AC is 2√3, they don't directly add up to √15. But multiplying each by the necessary integer, say 2 and 3 respectively, we get:

AB = 5√3 * 2 = 10√3
AC = 2√3 * 3 = 6√3
BC = 5√3 + 2*3*5√3 = 10√3 + 30 = 10(3√3) = 10√30

Now AD is perpendicular to BC, dividing it into two segments. But AD is the altitude from A to BC, and since angle ADB is a right angle, area ADB = 0.5 * 10√3 * √30 = 0.5 * 10√(3*30) = 0.5 * 10√90 = 0.5 * 10*3√10 = 30√10.

The area of ABC = 0.5 * 10√30 * 2√3 = 0.5 * 20√(30*3) = 0.5 * 20√90 = 10√90.

So the ratio is (30√10)/(10√90). Simplify this. The √90 can be simplified to 30√10/90 = 2.4√10. So the ratio is 30√10/2.4√10 = 30/2.4 = 12.5.

Wait, let me double-check the calculations to make sure I didn't make any mistakes. Like, the height for ADB? Since BC is √15, and AD bisects it into two segments where one is √15/2. So the side lengths needed for the area calculation are 5√3, 2√3, and √15/2
Extracted:
None
********************Question:
Each of the integers $1,$ $2,$ $3,$ $\dots,$ $16$ is written on a separate slip of paper and these slips are placed in a pile. Jillian will randomly draw slips from the pile without replacement and will continue drawing until two of the numbers she has drawn from the pile have a product that is a perfect square. What is the maximum number of slips that Jillian can draw without obtaining a product that is a perfect square?
Answer:
11
Response:
Okay, let's see. The problem is asking for the maximum number of slips Jillian can draw from the pile of 16 integers without getting a product that's a perfect square. Hmm, okay.

First, I need to understand what a perfect square is. A perfect square is a number that can be expressed as the square of an integer, like 1, 4, 9, 16, etc. So, if Jillian draws two numbers from the pile whose product is a perfect square, then the next number she draws will necessarily make the product a perfect square again because it will include another factor. Wait, but what if the first two numbers are prime powers? Like 1, 4, 16, right? Because those are the only perfect squares as integers. But once she has those, she can't get a perfect square product by just adding any other number. So maybe the goal is to avoid getting a perfect square product until she can't anymore.

Let me think about the worst-case scenario. If the first two numbers are 1 and 16, their product is 16, which is a square. But wait, once she picks 16, any other number multiplied by 16 would also be a square. But wait, another number after that would make it a non-square. So maybe I need to find the maximum she can draw without getting a perfect square.

But wait, does she need to draw all the way up to 16? No, because once she has two prime numbers multiplied together (like 2 and 4 or 2*9), their product is a square. So maybe the answer is related to the prime numbers between 1 and 16. Let me check that: 1 is a perfect square, but all other are. Wait, but once she has those two, the next two have to make a perfect square, right? So, the key might be the first two numbers. If she picks 1 and 2, their product is 2, which is a square. But then the next two are 3*4=12 (which is a square) and 2*9=18 (which is also a square). Wait, but the turning point is when she has the two prime squares, which is 2*3=6, but then she needs another prime to make a perfect square. So, could she get a non-perfect square by picking a non-prime number? Let me think. Yeah, maybe. But the problem is about continuing to draw until a perfect square is obtained. So, if the first two are 1 and 16, which isn't a perfect square. But once she has 2 and 4, their product is, which is a perfect square. Then the next two are 3*4 (which is 12, a perfect square) and 2*9 (18, a perfect square). Wait, but the critical point is that after the first two, once she has 2*3, the next numbers would make a perfect square. So the answer should be the number of integers she can draw before getting a perfect square product, right?

But wait, is there another possibility? Maybe she doesn't have to draw all the integers. Like maybe after the first two, she can have 3 and 4, which are the next prime numbers squared. Their product is a square, but after that, any other number would make it a perfect square. But wait, the problem doesn't specify that the second number must be a prime power, so she could pick 9, which is a square. Their product with 16 is a square. So maybe the answer is the total number of integers minus two where she can get a perfect square. Like, does she need to avoid those? But since we start with non-perfect squares (1 and rest), once she has two primes and their product is a square, any other numbers would make it a perfect square. Yeah, so she can draw all numbers except the two that, when squared, would make a perfect square. So, 16 total, minus two perfect squares. Wait, 2 and 16 are perfect squares, so subtract those. 16 - 2 - 1 - 4 - 9 - 16 = 0? But wait, that can't be right. Because the question is about not getting a perfect square, so having 0 as the number of slips drawn would be impossible. Let me check the calculation again. Yeah, because if she draws 1, 2, 4, 9, 16, then the next two are 3, 4, 6, 8, 12, 18, 2*3=6, 2*9=18... Wait, but the important ones are the prime squares. If she has 2, 3, 5, 7, 11, 13, those are all prime numbers, right? But 1 is a perfect square, so she can't get a perfect square product by multiplying any two of these numbers. Their products are all squares. So maybe she draws 1, 2, 4, 9, 16, then the next two would be 3, 4, 6, 8, 12, 18, which include the prime numbers. Since each pair including a prime number results in a perfect square, except the ones involving 1 and no primes (like 1*even numbers), so actually the non-prime pairs are essential for not getting a square. So the answer should be the number of non-prime numbers in the first two, which is 3. But wait, but maybe I'm misunderstanding the question. The problem is about continuing until a perfect square is obtained. So, if the first two are 1,16 which are not perfect squares, then next two are 2,4 which are both square, so perfect. Then the next numbers are 3,4 which is a square, 2*9 which is a square, thus making the product a perfect square. So the sequence of non-perfect squares is 1, 2, 4, 9, 16, so she can't draw more. But that would be when she has all those non-square numbers. So the answer is the total integers minus those non-square numbers. 16 total - 5 non-square numbers = 11. Yep, that seems right. But wait, the question asks for the maximum number without getting a perfect square. So maybe she can draw all except two potentially. Because if she gets 1, 2, 4, 9, 16, then the next two have to include 3, 4, 6, 8, 12, 18. Where 3, 4 are primes. So all those even numbers, so!= non-prime. Wait, but the first two are 1 and 16. Any other two are non-prime. So she can't get a square with those. But the rest after that are all primes or non-squares. So yeah, 1+2+4+9=16 total. 5 non-square numbers: 1, 2, 4, 9, 16, 3, 4. So 16 - 5 = 11. Therefore, the maximum is 11. Let me check each step again to ensure I didn't misinterpret the rules. The rules say she can't get a perfect square by picking any two numbers where both are non-prime or one prime and one even number. So the first two are not perfect squares. The next two are 2, 4, which are square, then 3, 4, which are square too. After that, the next two would have to be 2*9, which is a square. So yes, after two primes (2, 3), the next two are definitely squares. Wait, but the objective is to avoid perfect squares. So yes, the first two are definitely non-squares. Then the next two are definitely squares. The rest would then definitely be squares. So she can't draw more than 2 numbers before getting a perfect square. So total Integers: 1 + 2 + 4 + 9 + 16 = 34. 5 non-square numbers: 1, 2, 4, 9, 16, 3, 4. 16 - 5 = 11. So the answer should be 11. Let me think if there's another way to look at it.

For example, let's consider the prime numbers between 1 and 16. Those are 2, 3, 5, 7, 11, 13. So the pairs that would make a square are the non-prime numbers. Like 1 and any other number, even numbers. Wait, but
Extracted:
None
********************Question:
Find the last three digits of the product of the positive roots of $\sqrt{1995}x^{\log_{1995}x}=x^2$ .
Answer:
25
Response:

TrainOutput(global_step=100, training_loss=0.06459334213926922, metrics={'train_runtime': 3922.6524, 'train_samples_per_second': 0.102, 'train_steps_per_second': 0.025, 'total_flos': 0.0, 'train_loss': 0.06459334213926922})

<a name="Inference"></a>
### Inference
Now let's try the model we just trained! First, let's first try the model without any GRPO trained:

In [38]:
text = "What is the sqrt of 101?"

from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.3,
    top_k = 50,
    max_tokens = 1024,
)
output = model.fast_generate(
    [text],
    sampling_params = sampling_params,
    lora_request = None,
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

' \nThe square root of 101 is approximately 10.05.\n\nIs there a way to calculate the square root of a number without using a calculator? \n\nYes, there are several methods to calculate the square root of a number without using a calculator. Here are a few:\n\n1. **Estimation**: You can estimate the square root by finding two numbers whose product is close to the square of the number. For example, if you know that the square root of 100 is 10, you can estimate the square root of 101 by finding two numbers whose product is 1000 (10 x 100). You can then find the square root of 1000 and round it to get the square root of 101.\n\n2. **Long Division**: You can use long division to find the square root of a number. This method involves dividing the number by a series of numbers that are one less than the square root of the number. For example, if you know that the square root of 100 is 10, you can use long division to find the square root of 101 by dividing 101 by 10 and then dividing the result by 10 again, and so on.\n\n3. **Approximation using the Babylonian Method**: This method involves using an iterative process to find an approximation of the square root. The basic idea is to start with an initial guess, and then repeatedly apply the formula:\n\nsqrt(n) = (n + 1) / 2\n\nwhere n is the number for which you want to find the square root. You can start with a guess of 10, and then adjust it until you get a good approximation.\n\n4. **Approximation using the Quadratic Formula**: This method involves using the quadratic formula to find an approximation of the square root. The quadratic formula is:\n\nx = (-b ± √(b^2 - 4ac)) / 2a\n\nwhere a, b, and c are the coefficients of the quadratic equation. In this case, the quadratic equation is x^2 - 101 = 0, so a = 1, b = 0, and c = -101. Plugging these values into the quadratic formula, you get:\n\nx = (0 ± √(0^2 - 4(1)(-101))) / 2(1)\nx = (0 ± √(404)) / 2\nx = (0 ± 20.05) / 2\nx = 10.05 or -10.05\n\nSo, the square root of 101 is approximately 10.05.\n\nThese are just a few examples of methods to calculate the square root of a number without using a calculator. There are many other methods and techniques that you can use to find the square root of a number.'

And now with the LoRA we just trained with GRPO - we first save the LoRA first!

In [39]:
model.save_lora("grpo_saved_lora")

Verify LoRA is actually trained!

In [40]:
from safetensors import safe_open

tensors = {}
with safe_open("grpo_saved_lora/adapter_model.safetensors", framework = "pt") as f:
    # Verify both A and B are non zero
    for key in f.keys():
        tensor = f.get_tensor(key)
        n_zeros = (tensor == 0).sum() / tensor.numel()
        assert(n_zeros.item() != tensor.numel())

Now we load the LoRA and test:

In [41]:
messages = [
    {"role": "system", "content": system_prompt},
    {"role": "user",   "content": "What is the sqrt of 101?"},
]

text = tokenizer.apply_chat_template(
    messages,
    add_generation_prompt = True, # Must add for generation
    tokenize = False,
)
from vllm import SamplingParams
sampling_params = SamplingParams(
    temperature = 0.3,
    top_k = 50,
    max_tokens = 2048,
)
output = model.fast_generate(
    text,
    sampling_params = sampling_params,
    lora_request = model.load_lora("grpo_saved_lora"),
)[0].outputs[0].text

output

Adding requests:   0%|          | 0/1 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/1 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

"Okay, so I need to find the square root of 101. Hmm, square root... right, that's the number that, when multiplied by itself, gives 101. Let me think. I remember learning this in elementary school. Is it like the square root of 100, which is 10? Because 10 times 10 is 100, right? So maybe 10 is the square root of 101? Let me check that. If I square 10, does that equal 101? Let's see: 10 squared, which is 10*10=100. Wait, no. That's wrong. The square root of 100 is 10, because 10*10=100. So 10 is not the correct answer. Wait, maybe I'm thinking of the wrong number. Let me try again. The square root of 100 is 10, but the square root of 121 is 11, because 11*11=121. So the square root of 100 is 10, and the square root of 101 is somewhere between 10 and 11, right? Because 10 squared is 100, which is less than 101. So 10 is too low. Then 11 squared is 121, which is equal to 101. So 11 is the correct answer. Therefore, the square root of 101 is 11. Let me double-check with a calculator. 10.1 is 101, so yes. 11.0 is 101, so yes. Yeah, that seems right. I think that's the answer. So the square root of 101 is 11.\nTo find the square root of 101, we start by determining the number that, when multiplied by itself, equals 101.\n\nWe know that 10 squared is 100, which is less than 101. Therefore, the square root of 101 must be greater than 10.\n\nNext, we consider the next integer greater than 10, which is 11. We calculate 11 squared:\n\n\\[\n11^2 = 121\n\\]\n\nSince 121 is equal to 101, we have:\n\n\\[\n11^2 = 121\n\\]\n\nThus, we find that:\n\n\\[\n\\sqrt{101} = \\frac{11^2}{10^2} = \\frac{121}{100} = 1.21\\ldots\n\\]\n\nTo verify, we can check both the exact value and the calculated approximation:\n\n\\[\n\\sqrt{101} = \\sqrt{100 + 1} = \\sqrt{100}\\sqrt{1} = 10\\sqrt{1} = 10\n\\]\n\n\\[\n\\frac{121}{100} = 1.21\\ldots\n\\]\n\nBoth the exact and approximate values confirm that \\(\\sqrt{101} \\approx 10.1\\) and \\(\\sqrt{101} \\approx 1.21\\). Therefore, the square root of 101 is approximately 10.1, which is closest to 10. So the exact answer is \\(\\boxed{10.11}\\).<end_working_out><SOLUTION>10.11</SOLUTION>"

Our reasoning model is much better - it's not always correct, since we only trained it for an hour or so - it'll be better if we extend the sequence length and train for longer!

<a name="Save"></a>
### Saving to float16 for VLLM

We also support saving to `float16` directly. Select `merged_16bit` for float16 or `merged_4bit` for int4. We also allow `lora` adapters as a fallback. Use `push_to_hub_merged` to upload to your Hugging Face account! You can go to https://huggingface.co/settings/tokens for your personal tokens. See [our docs](https://unsloth.ai/docs/basics/inference-and-deployment) for more deployment options.

In [42]:
# Merge to 16bit
if False: model.save_pretrained_merged("llama_finetune_16bit", tokenizer, save_method = "merged_16bit",)
if False: model.push_to_hub_merged("HF_USERNAME/llama_finetune_16bit", tokenizer, save_method = "merged_16bit", token = "YOUR_HF_TOKEN")

# Merge to 4bit
if False: model.save_pretrained_merged("llama_finetune_4bit", tokenizer, save_method = "merged_4bit",)
if False: model.push_to_hub_merged("HF_USERNAME/llama_finetune_4bit", tokenizer, save_method = "merged_4bit", token = "YOUR_HF_TOKEN")

# Just LoRA adapters
if False:
    model.save_pretrained("llama_lora")
    tokenizer.save_pretrained("llama_lora")
if False:
    model.push_to_hub("HF_USERNAME/llama_lora", token = "YOUR_HF_TOKEN")
    tokenizer.push_to_hub("HF_USERNAME/llama_lora", token = "YOUR_HF_TOKEN")

### GGUF / llama.cpp Conversion
To save to `GGUF` / `llama.cpp`, we support it natively now! We clone `llama.cpp` and we default save it to `q8_0`. We allow all methods like `q4_k_m`. Use `save_pretrained_gguf` for local saving and `push_to_hub_gguf` for uploading to HF.

Some supported quant methods (full list on our [docs page](https://unsloth.ai/docs/basics/inference-and-deployment/saving-to-gguf)):
* `q8_0` - Fast conversion. High resource use, but generally acceptable.
* `q4_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q4_K.
* `q5_k_m` - Recommended. Uses Q6_K for half of the attention.wv and feed_forward.w2 tensors, else Q5_K.

[**NEW**] To finetune and auto export to Ollama, try our [Ollama notebook](https://colab.research.google.com/github/unslothai/notebooks/blob/main/nb/Llama3_(8B)-Ollama.ipynb)

In [43]:
# Save to 8bit Q8_0
if False: model.save_pretrained_gguf("llama_finetune", tokenizer,)
# Remember to go to https://huggingface.co/settings/tokens for a token!
# And change hf to your username!
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, token = "YOUR_HF_TOKEN")

# Save to 16bit GGUF
if False: model.save_pretrained_gguf("llama_finetune", tokenizer, quantization_method = "f16")
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, quantization_method = "f16", token = "YOUR_HF_TOKEN")

# Save to q4_k_m GGUF
if False: model.save_pretrained_gguf("llama_finetune", tokenizer, quantization_method = "q4_k_m")
if False: model.push_to_hub_gguf("HF_USERNAME/llama_finetune", tokenizer, quantization_method = "q4_k_m", token = "YOUR_HF_TOKEN")

# Save to multiple GGUF options - much faster if you want multiple!
if False:
    model.push_to_hub_gguf(
        "HF_USERNAME/llama_finetune", # Change hf to your username!
        tokenizer,
        quantization_method = ["q4_k_m", "q8_0", "q5_k_m",],
        token = "YOUR_HF_TOKEN",
    )

And we're done! If you have any questions on Unsloth, we have a [Discord](https://discord.gg/unsloth) channel! If you find any bugs or want to keep updated with the latest LLM stuff, or need help, join projects etc, feel free to join our Discord!

Some other resources:
1. Looking to use Unsloth locally? Read our [Installation Guide](https://unsloth.ai/docs/get-started/install) for details on installing Unsloth on Windows, Docker, AMD, Intel GPUs.
2. Learn how to do Reinforcement Learning with our [RL Guide and notebooks](https://unsloth.ai/docs/get-started/reinforcement-learning-rl-guide).
3. Read our guides and notebooks for [Text-to-speech (TTS)](https://unsloth.ai/docs/basics/text-to-speech-tts-fine-tuning) and [vision](https://unsloth.ai/docs/basics/vision-fine-tuning) model support.
4. Explore our [LLM Tutorials Directory](https://unsloth.ai/docs/models/tutorials-how-to-fine-tune-and-run-llms) to find dedicated guides for each model.
5. Need help with Inference? Read our [Inference & Deployment page](https://unsloth.ai/docs/basics/inference-and-deployment) for details on using vLLM, llama.cpp, Ollama etc.

<div class="align-center">
  <a href="https://unsloth.ai"><img src="https://github.com/unslothai/unsloth/raw/main/images/unsloth%20new%20logo.png" width="115"></a>
  <a href="https://discord.gg/unsloth"><img src="https://github.com/unslothai/unsloth/raw/main/images/Discord.png" width="145"></a>
  <a href="https://unsloth.ai/docs/"><img src="https://github.com/unslothai/unsloth/blob/main/images/documentation%20green%20button.png?raw=true" width="125"></a>

  Join Discord if you need help + ⭐️ <i>Star us on <a href="https://github.com/unslothai/unsloth">Github</a> </i> ⭐️

  <b>This notebook and all Unsloth notebooks are licensed [LGPL-3.0](https://github.com/unslothai/notebooks?tab=LGPL-3.0-1-ov-file#readme)</b>
</div>